### ISSUE TITLE
ERROR: AI model is unavailable

### ISSUE THREAD

**Issue by ThinkFar** [ourongxing/fake-raycast-backend#1]
Message: AI model is unavailable
Domain: ai
RC Version: 1.73.3

No AI functionality is operational after the latest update. 
It seems a model check has been implemented.

**Comment by ourongxing** [comment]
The issue has been fixed, but we still hope you can add the following rule to Surge to block raycast upgrades.
```
DOMAIN,releases.raycast.com,REJECT
```

**Comment by ThinkFar** [comment]
@ourongxing Thank you! Is it possible to implement an env variable that can be used to add a list or just one custom model? That way you wouldn't need to update the model name yourself and could have users select their preferred model, like the new cheaper GPT-4o model that just came out.

Regards!

**Comment by ourongxing** [comment]
GPT-4o has been added, but the plan you mentioned is not there because it is a low-frequency action.
